# Generated by Django 4.1 on 2022-08-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Choise',
            field=models.CharField(choices=[('AR', 'статья'), ('NW', 'сатья')], default='AR', max_length=2),
        ),
    ]
