# Generated by Django 4.1 on 2022-08-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_choise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('sport', 'Спорт'), ('politics', 'политика'), ('education', 'образование'), ('art', 'искусство')], max_length=225, unique=True, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
