# Generated by Django 4.1.2 on 2022-11-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_subscriberss_alter_subscribers_c_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='_Category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='_Post',
            new_name='Post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='_postcategory',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category', verbose_name='cat'),
        ),
    ]
