# Generated by Django 4.1 on 2022-09-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_name_alter_post_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('s', 'Спорт'), ('p', 'политика'), ('e', 'образование'), ('a', 'искусство')], max_length=225, unique=True, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Choise',
            field=models.CharField(choices=[('AR', 'статья'), ('NW', 'новость')], default='AR', max_length=2),
        ),
    ]
